//文件是自动生成,请勿手动修改.此类只有一个接口用于填充字典数据.
using System;
using System.Collections.Generic;
namespace Funcell.Cfg.Data
{
  public class DataConverter
  {
    private static bool _isLoaded = false;
    public static bool IsLoaded()
    {
        return _isLoaded;
    }
    public static void Load()
    {
        _isLoaded = false;
        return;
       DeclareDreamlandMonster.SetFillDataCallBack(DataDreamlandMonster.Convert);
       DeclareChangejobEquip.SetFillDataCallBack(DataChangejobEquip.Convert);
       DeclareSkillLevel.SetFillDataCallBack(DataSkillLevel.Convert);
       DeclareTaskDaily.SetFillDataCallBack(DataTaskDaily.Convert);
       DeclarePlayerSkillEvolution.SetFillDataCallBack(DataPlayerSkillEvolution.Convert);
       DeclareItem.SetFillDataCallBack(DataItem.Convert);
       DeclareClientGroupdrop.SetFillDataCallBack(DataClientGroupdrop.Convert);
       DeclareRetrieveRes.SetFillDataCallBack(DataRetrieveRes.Convert);
       DeclareHorseAttr.SetFillDataCallBack(DataHorseAttr.Convert);
       DeclareSoulcloneSet.SetFillDataCallBack(DataSoulcloneSet.Convert);
       DeclareEquipSuit.SetFillDataCallBack(DataEquipSuit.Convert);
       DeclareEquipCast.SetFillDataCallBack(DataEquipCast.Convert);
       DeclareBlood.SetFillDataCallBack(DataBlood.Convert);
       DeclareAchievement.SetFillDataCallBack(DataAchievement.Convert);
       DeclareClientDrop.SetFillDataCallBack(DataClientDrop.Convert);
       DeclareChangejob.SetFillDataCallBack(DataChangejob.Convert);
       DeclareDiamondinvestUp.SetFillDataCallBack(DataDiamondinvestUp.Convert);
       DeclareFightingSoul.SetFillDataCallBack(DataFightingSoul.Convert);
       DeclareNpc.SetFillDataCallBack(DataNpc.Convert);
       DeclareMonsterTalk.SetFillDataCallBack(DataMonsterTalk.Convert);
       DeclareGuide.SetFillDataCallBack(DataGuide.Convert);
       DeclareKingAllianceLevel.SetFillDataCallBack(DataKingAllianceLevel.Convert);
       DeclareTask.SetFillDataCallBack(DataTask.Convert);
       DeclareMasterSpiritArray.SetFillDataCallBack(DataMasterSpiritArray.Convert);
       DeclareUpdateReward.SetFillDataCallBack(DataUpdateReward.Convert);
       DeclareShopGift.SetFillDataCallBack(DataShopGift.Convert);
       DeclareGuildFightPersonal.SetFillDataCallBack(DataGuildFightPersonal.Convert);
       DeclarePet.SetFillDataCallBack(DataPet.Convert);
       DeclareKaifuThousandPeopleUp.SetFillDataCallBack(DataKaifuThousandPeopleUp.Convert);
       DeclareSyntheticSuitStone.SetFillDataCallBack(DataSyntheticSuitStone.Convert);
       DeclareMarriageDinner.SetFillDataCallBack(DataMarriageDinner.Convert);
       DeclareGrowthFundAll.SetFillDataCallBack(DataGrowthFundAll.Convert);
       DeclareCityWarAward.SetFillDataCallBack(DataCityWarAward.Convert);
       DeclareBuff.SetFillDataCallBack(DataBuff.Convert);
       DeclareBattleComboKill.SetFillDataCallBack(DataBattleComboKill.Convert);
       DeclareDiamondinvest.SetFillDataCallBack(DataDiamondinvest.Convert);
       DeclareStatueModel.SetFillDataCallBack(DataStatueModel.Convert);
       DeclarePray.SetFillDataCallBack(DataPray.Convert);
       DeclareMapsetting.SetFillDataCallBack(DataMapsetting.Convert);
       DeclareBossElementsTemple.SetFillDataCallBack(DataBossElementsTemple.Convert);
       DeclareFunctionStart.SetFillDataCallBack(DataFunctionStart.Convert);
       DeclareGuildAuction.SetFillDataCallBack(DataGuildAuction.Convert);
       DeclareBossHome.SetFillDataCallBack(DataBossHome.Convert);
       DeclareFunctionOpen.SetFillDataCallBack(DataFunctionOpen.Convert);
       DeclarePetSeal.SetFillDataCallBack(DataPetSeal.Convert);
       DeclareMelting.SetFillDataCallBack(DataMelting.Convert);
       DeclareEquipcloneReward.SetFillDataCallBack(DataEquipcloneReward.Convert);
       DeclareMilitaryRank.SetFillDataCallBack(DataMilitaryRank.Convert);
       DeclareFunctionVariable.SetFillDataCallBack(DataFunctionVariable.Convert);
       DeclareGlobal.SetFillDataCallBack(DataGlobal.Convert);
       DeclareFightingSoulLevel.SetFillDataCallBack(DataFightingSoulLevel.Convert);
       DeclarePeopleSoulSeal.SetFillDataCallBack(DataPeopleSoulSeal.Convert);
       DeclareQuestionWarehouse.SetFillDataCallBack(DataQuestionWarehouse.Convert);
       DeclareElementRuneSuit.SetFillDataCallBack(DataElementRuneSuit.Convert);
       DeclareCourage.SetFillDataCallBack(DataCourage.Convert);
       DeclareVipLevel.SetFillDataCallBack(DataVipLevel.Convert);
       DeclareMainTips.SetFillDataCallBack(DataMainTips.Convert);
       DeclareMasterTask.SetFillDataCallBack(DataMasterTask.Convert);
       DeclarePreload.SetFillDataCallBack(DataPreload.Convert);
       DeclareTombstone.SetFillDataCallBack(DataTombstone.Convert);
       DeclareGuildWelfare.SetFillDataCallBack(DataGuildWelfare.Convert);
       DeclareFashionStarStar.SetFillDataCallBack(DataFashionStarStar.Convert);
       DeclareFashionStar.SetFillDataCallBack(DataFashionStar.Convert);
       DeclareKingAllianceFeatsAward.SetFillDataCallBack(DataKingAllianceFeatsAward.Convert);
       DeclarePlayerTitle.SetFillDataCallBack(DataPlayerTitle.Convert);
       DeclareGuildQuestion.SetFillDataCallBack(DataGuildQuestion.Convert);
       DeclareGuildFightRanking.SetFillDataCallBack(DataGuildFightRanking.Convert);
       DeclareChangeJobFateStar.SetFillDataCallBack(DataChangeJobFateStar.Convert);
       DeclareCampBattleAward.SetFillDataCallBack(DataCampBattleAward.Convert);
       DeclareMasterLevel.SetFillDataCallBack(DataMasterLevel.Convert);
       DeclareEquipSkillSynthesis.SetFillDataCallBack(DataEquipSkillSynthesis.Convert);
       DeclareOnlineReward.SetFillDataCallBack(DataOnlineReward.Convert);
       DeclareSZZQAward.SetFillDataCallBack(DataSZZQAward.Convert);
       DeclareGuildTrial.SetFillDataCallBack(DataGuildTrial.Convert);
       DeclareScuffleWinAward.SetFillDataCallBack(DataScuffleWinAward.Convert);
       DeclareKuafuAlchemy.SetFillDataCallBack(DataKuafuAlchemy.Convert);
       DeclareCloakSkill.SetFillDataCallBack(DataCloakSkill.Convert);
       DeclareGuildFightCumulativeReward.SetFillDataCallBack(DataGuildFightCumulativeReward.Convert);
       DeclareGuildInvasion.SetFillDataCallBack(DataGuildInvasion.Convert);
       DeclareTips.SetFillDataCallBack(DataTips.Convert);
       DeclareSevendaypartygroup.SetFillDataCallBack(DataSevendaypartygroup.Convert);
       DeclareTaskSort.SetFillDataCallBack(DataTaskSort.Convert);
       DeclareTimelimitgift.SetFillDataCallBack(DataTimelimitgift.Convert);
       DeclareYyHuanJing.SetFillDataCallBack(DataYyHuanJing.Convert);
       DeclareMarriageCost.SetFillDataCallBack(DataMarriageCost.Convert);
       DeclareRechargeDailyTotal.SetFillDataCallBack(DataRechargeDailyTotal.Convert);
       DeclareWing.SetFillDataCallBack(DataWing.Convert);
       DeclareFashion.SetFillDataCallBack(DataFashion.Convert);
       DeclareEquipSkillCfg.SetFillDataCallBack(DataEquipSkillCfg.Convert);
       DeclareGuildIcon.SetFillDataCallBack(DataGuildIcon.Convert);
       DeclareChangeStar.SetFillDataCallBack(DataChangeStar.Convert);
       DeclareEquipFuse.SetFillDataCallBack(DataEquipFuse.Convert);
       DeclareSpecialMonster.SetFillDataCallBack(DataSpecialMonster.Convert);
       DeclareMasterTarget.SetFillDataCallBack(DataMasterTarget.Convert);
       DeclarePetSacrificeItem.SetFillDataCallBack(DataPetSacrificeItem.Convert);
       DeclareLevelReward.SetFillDataCallBack(DataLevelReward.Convert);
       DeclareChangejobStr.SetFillDataCallBack(DataChangejobStr.Convert);
       DeclarePhotoAction.SetFillDataCallBack(DataPhotoAction.Convert);
       DeclareReturnReward.SetFillDataCallBack(DataReturnReward.Convert);
       DeclareShieldingSymbol.SetFillDataCallBack(DataShieldingSymbol.Convert);
       DeclareMasterGraduate.SetFillDataCallBack(DataMasterGraduate.Convert);
       DeclareActiveReward.SetFillDataCallBack(DataActiveReward.Convert);
       DeclareCamp.SetFillDataCallBack(DataCamp.Convert);
       DeclarePetRuneName.SetFillDataCallBack(DataPetRuneName.Convert);
       DeclareRollDodge.SetFillDataCallBack(DataRollDodge.Convert);
       DeclareSkill.SetFillDataCallBack(DataSkill.Convert);
       DeclareTaskGender.SetFillDataCallBack(DataTaskGender.Convert);
       DeclarePeopleSoul.SetFillDataCallBack(DataPeopleSoul.Convert);
       DeclareElvesRunestar.SetFillDataCallBack(DataElvesRunestar.Convert);
       DeclareOffstring.SetFillDataCallBack(DataOffstring.Convert);
       DeclareBossGodRuins.SetFillDataCallBack(DataBossGodRuins.Convert);
       DeclareActiveBehavior.SetFillDataCallBack(DataActiveBehavior.Convert);
       DeclareSoulBeastsEquipSynthesis.SetFillDataCallBack(DataSoulBeastsEquipSynthesis.Convert);
       DeclareChallengeReward.SetFillDataCallBack(DataChallengeReward.Convert);
       DeclareHorseStar.SetFillDataCallBack(DataHorseStar.Convert);
       DeclareMedal.SetFillDataCallBack(DataMedal.Convert);
       DeclareTaskBattlefield.SetFillDataCallBack(DataTaskBattlefield.Convert);
       DeclareSevendayparty.SetFillDataCallBack(DataSevendayparty.Convert);
       DeclareDeviceMatchConfig.SetFillDataCallBack(DataDeviceMatchConfig.Convert);
       DeclareMarriageRing.SetFillDataCallBack(DataMarriageRing.Convert);
       DeclarePlayerTitleRune.SetFillDataCallBack(DataPlayerTitleRune.Convert);
       DeclareMasterKeepsake.SetFillDataCallBack(DataMasterKeepsake.Convert);
       DeclareShare.SetFillDataCallBack(DataShare.Convert);
       DeclareSignReward.SetFillDataCallBack(DataSignReward.Convert);
       DeclareGuildTrialReward.SetFillDataCallBack(DataGuildTrialReward.Convert);
       DeclareKuafuGuildBattle.SetFillDataCallBack(DataKuafuGuildBattle.Convert);
       DeclarePetAddattribute.SetFillDataCallBack(DataPetAddattribute.Convert);
       DeclareWingInfo.SetFillDataCallBack(DataWingInfo.Convert);
       DeclareMarriageZodiac.SetFillDataCallBack(DataMarriageZodiac.Convert);
       DeclareGuildDonate.SetFillDataCallBack(DataGuildDonate.Convert);
       DeclareGuildBonfire.SetFillDataCallBack(DataGuildBonfire.Convert);
       DeclareElementRuneLevel.SetFillDataCallBack(DataElementRuneLevel.Convert);
       DeclareCloneMap.SetFillDataCallBack(DataCloneMap.Convert);
       DeclareCiyuanSeal.SetFillDataCallBack(DataCiyuanSeal.Convert);
       DeclareGuildCollege.SetFillDataCallBack(DataGuildCollege.Convert);
       DeclareElvesRune.SetFillDataCallBack(DataElvesRune.Convert);
       DeclareBossSoulBeasts.SetFillDataCallBack(DataBossSoulBeasts.Convert);
       DeclareCharacters.SetFillDataCallBack(DataCharacters.Convert);
       DeclareGuideItem.SetFillDataCallBack(DataGuideItem.Convert);
       DeclareWingStar.SetFillDataCallBack(DataWingStar.Convert);
       DeclareBetterPlace.SetFillDataCallBack(DataBetterPlace.Convert);
       DeclareHorseMythical.SetFillDataCallBack(DataHorseMythical.Convert);
       DeclareSoulBeasts.SetFillDataCallBack(DataSoulBeasts.Convert);
       DeclareSoulBeastsEquip.SetFillDataCallBack(DataSoulBeastsEquip.Convert);
       DeclareKaifuActivityBOSS.SetFillDataCallBack(DataKaifuActivityBOSS.Convert);
       DeclareMonster.SetFillDataCallBack(DataMonster.Convert);
       DeclareRank.SetFillDataCallBack(DataRank.Convert);
       DeclareAttributeAdd.SetFillDataCallBack(DataAttributeAdd.Convert);
       DeclareActiveWeek.SetFillDataCallBack(DataActiveWeek.Convert);
       DeclareElvesAdvanced.SetFillDataCallBack(DataElvesAdvanced.Convert);
       DeclareEquipRefi.SetFillDataCallBack(DataEquipRefi.Convert);
       DeclareEquipStar.SetFillDataCallBack(DataEquipStar.Convert);
       DeclareKuafuAlchemySpirit.SetFillDataCallBack(DataKuafuAlchemySpirit.Convert);
       DeclareFriendIntimacy.SetFillDataCallBack(DataFriendIntimacy.Convert);
       DeclareGroundBuff.SetFillDataCallBack(DataGroundBuff.Convert);
       DeclareFightSoulHunting.SetFillDataCallBack(DataFightSoulHunting.Convert);
       DeclareScreenEffect.SetFillDataCallBack(DataScreenEffect.Convert);
       DeclareMilitaryRankTask.SetFillDataCallBack(DataMilitaryRankTask.Convert);
       DeclareCityWar.SetFillDataCallBack(DataCityWar.Convert);
       DeclareTaskConquer.SetFillDataCallBack(DataTaskConquer.Convert);
       DeclareShengwuAttr.SetFillDataCallBack(DataShengwuAttr.Convert);
       DeclareRandomName.SetFillDataCallBack(DataRandomName.Convert);
       DeclareGodTools.SetFillDataCallBack(DataGodTools.Convert);
       DeclareGodToolsStar.SetFillDataCallBack(DataGodToolsStar.Convert);
       DeclareBossPersonal.SetFillDataCallBack(DataBossPersonal.Convert);
       DeclareGuildUp.SetFillDataCallBack(DataGuildUp.Convert);
       DeclarePictureTitle.SetFillDataCallBack(DataPictureTitle.Convert);
       DeclareElvesStar.SetFillDataCallBack(DataElvesStar.Convert);
       DeclareShenwuAddatt.SetFillDataCallBack(DataShenwuAddatt.Convert);
       DeclareRandTips.SetFillDataCallBack(DataRandTips.Convert);
       DeclareCreatePlayerCfg.SetFillDataCallBack(DataCreatePlayerCfg.Convert);
       DeclareActiveRune.SetFillDataCallBack(DataActiveRune.Convert);
       DeclarePrayCost.SetFillDataCallBack(DataPrayCost.Convert);
       DeclareTaskChapter.SetFillDataCallBack(DataTaskChapter.Convert);
       DeclareRYZCAward.SetFillDataCallBack(DataRYZCAward.Convert);
       DeclareKingFightFeatsAward.SetFillDataCallBack(DataKingFightFeatsAward.Convert);
       DeclareSZZQScoreAward.SetFillDataCallBack(DataSZZQScoreAward.Convert);
       DeclareAchMedal.SetFillDataCallBack(DataAchMedal.Convert);
       DeclareARScale.SetFillDataCallBack(DataARScale.Convert);
       DeclareRechargeDaygift.SetFillDataCallBack(DataRechargeDaygift.Convert);
       DeclareJump.SetFillDataCallBack(DataJump.Convert);
       DeclareHorseMythicalGift.SetFillDataCallBack(DataHorseMythicalGift.Convert);
       DeclareTaskTalk.SetFillDataCallBack(DataTaskTalk.Convert);
       DeclareMessageString.SetFillDataCallBack(DataMessageString.Convert);
       DeclareHallowsAttr.SetFillDataCallBack(DataHallowsAttr.Convert);
       DeclareWorldQuestion.SetFillDataCallBack(DataWorldQuestion.Convert);
       DeclareElementRune.SetFillDataCallBack(DataElementRune.Convert);
       DeclareColor.SetFillDataCallBack(DataColor.Convert);
       DeclareMarriageAttribute.SetFillDataCallBack(DataMarriageAttribute.Convert);
       DeclareGoddessbadge.SetFillDataCallBack(DataGoddessbadge.Convert);
       DeclareTaskGuide.SetFillDataCallBack(DataTaskGuide.Convert);
       DeclareHelp.SetFillDataCallBack(DataHelp.Convert);
       DeclareMarriagePatron.SetFillDataCallBack(DataMarriagePatron.Convert);
       DeclareAncientBoss.SetFillDataCallBack(DataAncientBoss.Convert);
       DeclareKingFightLevel.SetFillDataCallBack(DataKingFightLevel.Convert);
       DeclareMasterHoly.SetFillDataCallBack(DataMasterHoly.Convert);
       DeclareMarriage.SetFillDataCallBack(DataMarriage.Convert);
       DeclareHallowsModel.SetFillDataCallBack(DataHallowsModel.Convert);
       DeclareCampBattleRank.SetFillDataCallBack(DataCampBattleRank.Convert);
       DeclareGuildFightReward.SetFillDataCallBack(DataGuildFightReward.Convert);
       DeclareTempleAward.SetFillDataCallBack(DataTempleAward.Convert);
       DeclareTemple.SetFillDataCallBack(DataTemple.Convert);
       DeclareHeraldry.SetFillDataCallBack(DataHeraldry.Convert);
       DeclareActiveAttribute.SetFillDataCallBack(DataActiveAttribute.Convert);
       DeclareStrengthenVfx.SetFillDataCallBack(DataStrengthenVfx.Convert);
       DeclareKuafuAlchemySkill.SetFillDataCallBack(DataKuafuAlchemySkill.Convert);
       DeclareDiamondinvestLevel.SetFillDataCallBack(DataDiamondinvestLevel.Convert);
       DeclareEquip.SetFillDataCallBack(DataEquip.Convert);
       DeclareHorseUp.SetFillDataCallBack(DataHorseUp.Convert);
       DeclareEquipSeal.SetFillDataCallBack(DataEquipSeal.Convert);
       DeclareWingAttr.SetFillDataCallBack(DataWingAttr.Convert);
       DeclarePetLevel.SetFillDataCallBack(DataPetLevel.Convert);
       DeclareGather.SetFillDataCallBack(DataGather.Convert);
       DeclarePowerAnalysis.SetFillDataCallBack(DataPowerAnalysis.Convert);
       DeclareUIConfig.SetFillDataCallBack(DataUIConfig.Convert);
       DeclareElementRuneSoul.SetFillDataCallBack(DataElementRuneSoul.Convert);
       DeclareGmCmd.SetFillDataCallBack(DataGmCmd.Convert);
       DeclareTaskBranch.SetFillDataCallBack(DataTaskBranch.Convert);
       DeclareBagGrid.SetFillDataCallBack(DataBagGrid.Convert);
       DeclareScuffleLevel.SetFillDataCallBack(DataScuffleLevel.Convert);
       DeclareRechargeAward.SetFillDataCallBack(DataRechargeAward.Convert);
       DeclareGuildMonsterIntrusion.SetFillDataCallBack(DataGuildMonsterIntrusion.Convert);
       DeclareActiveMedal.SetFillDataCallBack(DataActiveMedal.Convert);
       DeclareActivityPrompt.SetFillDataCallBack(DataActivityPrompt.Convert);
       DeclareWingUp.SetFillDataCallBack(DataWingUp.Convert);
       DeclareFashionLink.SetFillDataCallBack(DataFashionLink.Convert);
       DeclareVip.SetFillDataCallBack(DataVip.Convert);
       DeclarePhotoFilter.SetFillDataCallBack(DataPhotoFilter.Convert);
       DeclareSevendayLogin.SetFillDataCallBack(DataSevendayLogin.Convert);
       DeclareGuildOfficial.SetFillDataCallBack(DataGuildOfficial.Convert);
       DeclareComboKill.SetFillDataCallBack(DataComboKill.Convert);
       DeclareHorseMythicalLink.SetFillDataCallBack(DataHorseMythicalLink.Convert);
       DeclareKaifuGuildlStarcraft.SetFillDataCallBack(DataKaifuGuildlStarcraft.Convert);
       DeclareModelConfig.SetFillDataCallBack(DataModelConfig.Convert);
       DeclareSoulBeastsEquipLevel.SetFillDataCallBack(DataSoulBeastsEquipLevel.Convert);
       DeclareEquipSynthesis.SetFillDataCallBack(DataEquipSynthesis.Convert);
       DeclareTaskEscort.SetFillDataCallBack(DataTaskEscort.Convert);
       DeclareWorldQuestionReward.SetFillDataCallBack(DataWorldQuestionReward.Convert);
       DeclareKuafuStatueEvaluate.SetFillDataCallBack(DataKuafuStatueEvaluate.Convert);
       DeclareGuildFightContinuousReward.SetFillDataCallBack(DataGuildFightContinuousReward.Convert);
       DeclareTaskLine.SetFillDataCallBack(DataTaskLine.Convert);
       DeclarePlayerSkill.SetFillDataCallBack(DataPlayerSkill.Convert);
       DeclareBossgodclone.SetFillDataCallBack(DataBossgodclone.Convert);
       DeclareKingAllianceSeasonAward.SetFillDataCallBack(DataKingAllianceSeasonAward.Convert);
       DeclareElvesRunelevel.SetFillDataCallBack(DataElvesRunelevel.Convert);
       DeclarePlayerGodHead.SetFillDataCallBack(DataPlayerGodHead.Convert);
       DeclareFunctionAlert.SetFillDataCallBack(DataFunctionAlert.Convert);
       DeclareCinematic.SetFillDataCallBack(DataCinematic.Convert);
       DeclareKingFightSeasonAward.SetFillDataCallBack(DataKingFightSeasonAward.Convert);
       DeclareShengwuModel.SetFillDataCallBack(DataShengwuModel.Convert);
       DeclareBossGodRuinsMonster.SetFillDataCallBack(DataBossGodRuinsMonster.Convert);
       DeclareSevendaypartystrong.SetFillDataCallBack(DataSevendaypartystrong.Convert);
       DeclareJJCAeward.SetFillDataCallBack(DataJJCAeward.Convert);
       DeclareFriendItem.SetFillDataCallBack(DataFriendItem.Convert);
       DeclareGmMainFunction.SetFillDataCallBack(DataGmMainFunction.Convert);
       DeclareAutoUseMedicine.SetFillDataCallBack(DataAutoUseMedicine.Convert);
       DeclareGrowthFund.SetFillDataCallBack(DataGrowthFund.Convert);
       DeclareAchievementType.SetFillDataCallBack(DataAchievementType.Convert);
       DeclarePlayerOccupation.SetFillDataCallBack(DataPlayerOccupation.Convert);
        _isLoaded = true;
    }
    public static void FillData(bool needSleep = true,int sleepLen = 2)
    {
        
       var DreamlandMonsterDict = DeclareDreamlandMonster.CacheData;
       DreamlandMonsterDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ChangejobEquipDict = DeclareChangejobEquip.CacheData;
       ChangejobEquipDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var SkillLevelDict = DeclareSkillLevel.CacheData;
       SkillLevelDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var TaskDailyDict = DeclareTaskDaily.CacheData;
       TaskDailyDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var PlayerSkillEvolutionDict = DeclarePlayerSkillEvolution.CacheData;
       PlayerSkillEvolutionDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ItemDict = DeclareItem.CacheData;
       ItemDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ClientGroupdropDict = DeclareClientGroupdrop.CacheData;
       ClientGroupdropDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var RetrieveResDict = DeclareRetrieveRes.CacheData;
       RetrieveResDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var HorseAttrDict = DeclareHorseAttr.CacheData;
       HorseAttrDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var SoulcloneSetDict = DeclareSoulcloneSet.CacheData;
       SoulcloneSetDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var EquipSuitDict = DeclareEquipSuit.CacheData;
       EquipSuitDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var EquipCastDict = DeclareEquipCast.CacheData;
       EquipCastDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var BloodDict = DeclareBlood.CacheData;
       BloodDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var AchievementDict = DeclareAchievement.CacheData;
       AchievementDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ClientDropDict = DeclareClientDrop.CacheData;
       ClientDropDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ChangejobDict = DeclareChangejob.CacheData;
       ChangejobDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var DiamondinvestUpDict = DeclareDiamondinvestUp.CacheData;
       DiamondinvestUpDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var FightingSoulDict = DeclareFightingSoul.CacheData;
       FightingSoulDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var NpcDict = DeclareNpc.CacheData;
       NpcDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MonsterTalkDict = DeclareMonsterTalk.CacheData;
       MonsterTalkDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GuideDict = DeclareGuide.CacheData;
       GuideDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var KingAllianceLevelDict = DeclareKingAllianceLevel.CacheData;
       KingAllianceLevelDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var TaskDict = DeclareTask.CacheData;
       TaskDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MasterSpiritArrayDict = DeclareMasterSpiritArray.CacheData;
       MasterSpiritArrayDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var UpdateRewardDict = DeclareUpdateReward.CacheData;
       UpdateRewardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ShopGiftDict = DeclareShopGift.CacheData;
       ShopGiftDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GuildFightPersonalDict = DeclareGuildFightPersonal.CacheData;
       GuildFightPersonalDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var PetDict = DeclarePet.CacheData;
       PetDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var KaifuThousandPeopleUpDict = DeclareKaifuThousandPeopleUp.CacheData;
       KaifuThousandPeopleUpDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var SyntheticSuitStoneDict = DeclareSyntheticSuitStone.CacheData;
       SyntheticSuitStoneDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MarriageDinnerDict = DeclareMarriageDinner.CacheData;
       MarriageDinnerDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GrowthFundAllDict = DeclareGrowthFundAll.CacheData;
       GrowthFundAllDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var CityWarAwardDict = DeclareCityWarAward.CacheData;
       CityWarAwardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var BuffDict = DeclareBuff.CacheData;
       BuffDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var BattleComboKillDict = DeclareBattleComboKill.CacheData;
       BattleComboKillDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var DiamondinvestDict = DeclareDiamondinvest.CacheData;
       DiamondinvestDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var StatueModelDict = DeclareStatueModel.CacheData;
       StatueModelDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var PrayDict = DeclarePray.CacheData;
       PrayDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MapsettingDict = DeclareMapsetting.CacheData;
       MapsettingDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var BossElementsTempleDict = DeclareBossElementsTemple.CacheData;
       BossElementsTempleDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var FunctionStartDict = DeclareFunctionStart.CacheData;
       FunctionStartDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GuildAuctionDict = DeclareGuildAuction.CacheData;
       GuildAuctionDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var BossHomeDict = DeclareBossHome.CacheData;
       BossHomeDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var FunctionOpenDict = DeclareFunctionOpen.CacheData;
       FunctionOpenDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var PetSealDict = DeclarePetSeal.CacheData;
       PetSealDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MeltingDict = DeclareMelting.CacheData;
       MeltingDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var EquipcloneRewardDict = DeclareEquipcloneReward.CacheData;
       EquipcloneRewardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MilitaryRankDict = DeclareMilitaryRank.CacheData;
       MilitaryRankDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var FunctionVariableDict = DeclareFunctionVariable.CacheData;
       FunctionVariableDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GlobalDict = DeclareGlobal.CacheData;
       GlobalDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var FightingSoulLevelDict = DeclareFightingSoulLevel.CacheData;
       FightingSoulLevelDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var PeopleSoulSealDict = DeclarePeopleSoulSeal.CacheData;
       PeopleSoulSealDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var QuestionWarehouseDict = DeclareQuestionWarehouse.CacheData;
       QuestionWarehouseDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ElementRuneSuitDict = DeclareElementRuneSuit.CacheData;
       ElementRuneSuitDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var CourageDict = DeclareCourage.CacheData;
       CourageDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var VipLevelDict = DeclareVipLevel.CacheData;
       VipLevelDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MainTipsDict = DeclareMainTips.CacheData;
       MainTipsDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MasterTaskDict = DeclareMasterTask.CacheData;
       MasterTaskDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var PreloadDict = DeclarePreload.CacheData;
       PreloadDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var TombstoneDict = DeclareTombstone.CacheData;
       TombstoneDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GuildWelfareDict = DeclareGuildWelfare.CacheData;
       GuildWelfareDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var FashionStarStarDict = DeclareFashionStarStar.CacheData;
       FashionStarStarDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var FashionStarDict = DeclareFashionStar.CacheData;
       FashionStarDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var KingAllianceFeatsAwardDict = DeclareKingAllianceFeatsAward.CacheData;
       KingAllianceFeatsAwardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var PlayerTitleDict = DeclarePlayerTitle.CacheData;
       PlayerTitleDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GuildQuestionDict = DeclareGuildQuestion.CacheData;
       GuildQuestionDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GuildFightRankingDict = DeclareGuildFightRanking.CacheData;
       GuildFightRankingDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ChangeJobFateStarDict = DeclareChangeJobFateStar.CacheData;
       ChangeJobFateStarDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var CampBattleAwardDict = DeclareCampBattleAward.CacheData;
       CampBattleAwardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MasterLevelDict = DeclareMasterLevel.CacheData;
       MasterLevelDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var EquipSkillSynthesisDict = DeclareEquipSkillSynthesis.CacheData;
       EquipSkillSynthesisDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var OnlineRewardDict = DeclareOnlineReward.CacheData;
       OnlineRewardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var SZZQAwardDict = DeclareSZZQAward.CacheData;
       SZZQAwardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GuildTrialDict = DeclareGuildTrial.CacheData;
       GuildTrialDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ScuffleWinAwardDict = DeclareScuffleWinAward.CacheData;
       ScuffleWinAwardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var KuafuAlchemyDict = DeclareKuafuAlchemy.CacheData;
       KuafuAlchemyDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var CloakSkillDict = DeclareCloakSkill.CacheData;
       CloakSkillDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GuildFightCumulativeRewardDict = DeclareGuildFightCumulativeReward.CacheData;
       GuildFightCumulativeRewardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GuildInvasionDict = DeclareGuildInvasion.CacheData;
       GuildInvasionDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var TipsDict = DeclareTips.CacheData;
       TipsDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var SevendaypartygroupDict = DeclareSevendaypartygroup.CacheData;
       SevendaypartygroupDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var TaskSortDict = DeclareTaskSort.CacheData;
       TaskSortDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var TimelimitgiftDict = DeclareTimelimitgift.CacheData;
       TimelimitgiftDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var YyHuanJingDict = DeclareYyHuanJing.CacheData;
       YyHuanJingDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MarriageCostDict = DeclareMarriageCost.CacheData;
       MarriageCostDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var RechargeDailyTotalDict = DeclareRechargeDailyTotal.CacheData;
       RechargeDailyTotalDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var WingDict = DeclareWing.CacheData;
       WingDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var FashionDict = DeclareFashion.CacheData;
       FashionDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var EquipSkillCfgDict = DeclareEquipSkillCfg.CacheData;
       EquipSkillCfgDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GuildIconDict = DeclareGuildIcon.CacheData;
       GuildIconDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ChangeStarDict = DeclareChangeStar.CacheData;
       ChangeStarDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var EquipFuseDict = DeclareEquipFuse.CacheData;
       EquipFuseDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var SpecialMonsterDict = DeclareSpecialMonster.CacheData;
       SpecialMonsterDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MasterTargetDict = DeclareMasterTarget.CacheData;
       MasterTargetDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var PetSacrificeItemDict = DeclarePetSacrificeItem.CacheData;
       PetSacrificeItemDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var LevelRewardDict = DeclareLevelReward.CacheData;
       LevelRewardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ChangejobStrDict = DeclareChangejobStr.CacheData;
       ChangejobStrDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var PhotoActionDict = DeclarePhotoAction.CacheData;
       PhotoActionDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ReturnRewardDict = DeclareReturnReward.CacheData;
       ReturnRewardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ShieldingSymbolDict = DeclareShieldingSymbol.CacheData;
       ShieldingSymbolDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MasterGraduateDict = DeclareMasterGraduate.CacheData;
       MasterGraduateDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ActiveRewardDict = DeclareActiveReward.CacheData;
       ActiveRewardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var CampDict = DeclareCamp.CacheData;
       CampDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var PetRuneNameDict = DeclarePetRuneName.CacheData;
       PetRuneNameDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var RollDodgeDict = DeclareRollDodge.CacheData;
       RollDodgeDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var SkillDict = DeclareSkill.CacheData;
       SkillDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var TaskGenderDict = DeclareTaskGender.CacheData;
       TaskGenderDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var PeopleSoulDict = DeclarePeopleSoul.CacheData;
       PeopleSoulDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ElvesRunestarDict = DeclareElvesRunestar.CacheData;
       ElvesRunestarDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var OffstringDict = DeclareOffstring.CacheData;
       OffstringDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var BossGodRuinsDict = DeclareBossGodRuins.CacheData;
       BossGodRuinsDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ActiveBehaviorDict = DeclareActiveBehavior.CacheData;
       ActiveBehaviorDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var SoulBeastsEquipSynthesisDict = DeclareSoulBeastsEquipSynthesis.CacheData;
       SoulBeastsEquipSynthesisDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ChallengeRewardDict = DeclareChallengeReward.CacheData;
       ChallengeRewardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var HorseStarDict = DeclareHorseStar.CacheData;
       HorseStarDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MedalDict = DeclareMedal.CacheData;
       MedalDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var TaskBattlefieldDict = DeclareTaskBattlefield.CacheData;
       TaskBattlefieldDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var SevendaypartyDict = DeclareSevendayparty.CacheData;
       SevendaypartyDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var DeviceMatchConfigDict = DeclareDeviceMatchConfig.CacheData;
       DeviceMatchConfigDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MarriageRingDict = DeclareMarriageRing.CacheData;
       MarriageRingDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var PlayerTitleRuneDict = DeclarePlayerTitleRune.CacheData;
       PlayerTitleRuneDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MasterKeepsakeDict = DeclareMasterKeepsake.CacheData;
       MasterKeepsakeDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ShareDict = DeclareShare.CacheData;
       ShareDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var SignRewardDict = DeclareSignReward.CacheData;
       SignRewardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GuildTrialRewardDict = DeclareGuildTrialReward.CacheData;
       GuildTrialRewardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var KuafuGuildBattleDict = DeclareKuafuGuildBattle.CacheData;
       KuafuGuildBattleDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var PetAddattributeDict = DeclarePetAddattribute.CacheData;
       PetAddattributeDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var WingInfoDict = DeclareWingInfo.CacheData;
       WingInfoDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MarriageZodiacDict = DeclareMarriageZodiac.CacheData;
       MarriageZodiacDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GuildDonateDict = DeclareGuildDonate.CacheData;
       GuildDonateDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GuildBonfireDict = DeclareGuildBonfire.CacheData;
       GuildBonfireDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ElementRuneLevelDict = DeclareElementRuneLevel.CacheData;
       ElementRuneLevelDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var CloneMapDict = DeclareCloneMap.CacheData;
       CloneMapDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var CiyuanSealDict = DeclareCiyuanSeal.CacheData;
       CiyuanSealDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GuildCollegeDict = DeclareGuildCollege.CacheData;
       GuildCollegeDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ElvesRuneDict = DeclareElvesRune.CacheData;
       ElvesRuneDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var BossSoulBeastsDict = DeclareBossSoulBeasts.CacheData;
       BossSoulBeastsDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var CharactersDict = DeclareCharacters.CacheData;
       CharactersDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GuideItemDict = DeclareGuideItem.CacheData;
       GuideItemDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var WingStarDict = DeclareWingStar.CacheData;
       WingStarDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var BetterPlaceDict = DeclareBetterPlace.CacheData;
       BetterPlaceDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var HorseMythicalDict = DeclareHorseMythical.CacheData;
       HorseMythicalDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var SoulBeastsDict = DeclareSoulBeasts.CacheData;
       SoulBeastsDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var SoulBeastsEquipDict = DeclareSoulBeastsEquip.CacheData;
       SoulBeastsEquipDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var KaifuActivityBOSSDict = DeclareKaifuActivityBOSS.CacheData;
       KaifuActivityBOSSDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MonsterDict = DeclareMonster.CacheData;
       MonsterDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var RankDict = DeclareRank.CacheData;
       RankDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var AttributeAddDict = DeclareAttributeAdd.CacheData;
       AttributeAddDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ActiveWeekDict = DeclareActiveWeek.CacheData;
       ActiveWeekDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ElvesAdvancedDict = DeclareElvesAdvanced.CacheData;
       ElvesAdvancedDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var EquipRefiDict = DeclareEquipRefi.CacheData;
       EquipRefiDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var EquipStarDict = DeclareEquipStar.CacheData;
       EquipStarDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var KuafuAlchemySpiritDict = DeclareKuafuAlchemySpirit.CacheData;
       KuafuAlchemySpiritDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var FriendIntimacyDict = DeclareFriendIntimacy.CacheData;
       FriendIntimacyDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GroundBuffDict = DeclareGroundBuff.CacheData;
       GroundBuffDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var FightSoulHuntingDict = DeclareFightSoulHunting.CacheData;
       FightSoulHuntingDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ScreenEffectDict = DeclareScreenEffect.CacheData;
       ScreenEffectDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MilitaryRankTaskDict = DeclareMilitaryRankTask.CacheData;
       MilitaryRankTaskDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var CityWarDict = DeclareCityWar.CacheData;
       CityWarDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var TaskConquerDict = DeclareTaskConquer.CacheData;
       TaskConquerDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ShengwuAttrDict = DeclareShengwuAttr.CacheData;
       ShengwuAttrDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var RandomNameDict = DeclareRandomName.CacheData;
       RandomNameDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GodToolsDict = DeclareGodTools.CacheData;
       GodToolsDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GodToolsStarDict = DeclareGodToolsStar.CacheData;
       GodToolsStarDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var BossPersonalDict = DeclareBossPersonal.CacheData;
       BossPersonalDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GuildUpDict = DeclareGuildUp.CacheData;
       GuildUpDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var PictureTitleDict = DeclarePictureTitle.CacheData;
       PictureTitleDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ElvesStarDict = DeclareElvesStar.CacheData;
       ElvesStarDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ShenwuAddattDict = DeclareShenwuAddatt.CacheData;
       ShenwuAddattDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var RandTipsDict = DeclareRandTips.CacheData;
       RandTipsDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var CreatePlayerCfgDict = DeclareCreatePlayerCfg.CacheData;
       CreatePlayerCfgDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ActiveRuneDict = DeclareActiveRune.CacheData;
       ActiveRuneDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var PrayCostDict = DeclarePrayCost.CacheData;
       PrayCostDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var TaskChapterDict = DeclareTaskChapter.CacheData;
       TaskChapterDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var RYZCAwardDict = DeclareRYZCAward.CacheData;
       RYZCAwardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var KingFightFeatsAwardDict = DeclareKingFightFeatsAward.CacheData;
       KingFightFeatsAwardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var SZZQScoreAwardDict = DeclareSZZQScoreAward.CacheData;
       SZZQScoreAwardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var AchMedalDict = DeclareAchMedal.CacheData;
       AchMedalDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ARScaleDict = DeclareARScale.CacheData;
       ARScaleDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var RechargeDaygiftDict = DeclareRechargeDaygift.CacheData;
       RechargeDaygiftDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var JumpDict = DeclareJump.CacheData;
       JumpDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var HorseMythicalGiftDict = DeclareHorseMythicalGift.CacheData;
       HorseMythicalGiftDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var TaskTalkDict = DeclareTaskTalk.CacheData;
       TaskTalkDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MessageStringDict = DeclareMessageString.CacheData;
       MessageStringDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var HallowsAttrDict = DeclareHallowsAttr.CacheData;
       HallowsAttrDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var WorldQuestionDict = DeclareWorldQuestion.CacheData;
       WorldQuestionDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ElementRuneDict = DeclareElementRune.CacheData;
       ElementRuneDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ColorDict = DeclareColor.CacheData;
       ColorDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MarriageAttributeDict = DeclareMarriageAttribute.CacheData;
       MarriageAttributeDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GoddessbadgeDict = DeclareGoddessbadge.CacheData;
       GoddessbadgeDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var TaskGuideDict = DeclareTaskGuide.CacheData;
       TaskGuideDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var HelpDict = DeclareHelp.CacheData;
       HelpDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MarriagePatronDict = DeclareMarriagePatron.CacheData;
       MarriagePatronDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var AncientBossDict = DeclareAncientBoss.CacheData;
       AncientBossDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var KingFightLevelDict = DeclareKingFightLevel.CacheData;
       KingFightLevelDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MasterHolyDict = DeclareMasterHoly.CacheData;
       MasterHolyDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var MarriageDict = DeclareMarriage.CacheData;
       MarriageDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var HallowsModelDict = DeclareHallowsModel.CacheData;
       HallowsModelDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var CampBattleRankDict = DeclareCampBattleRank.CacheData;
       CampBattleRankDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GuildFightRewardDict = DeclareGuildFightReward.CacheData;
       GuildFightRewardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var TempleAwardDict = DeclareTempleAward.CacheData;
       TempleAwardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var TempleDict = DeclareTemple.CacheData;
       TempleDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var HeraldryDict = DeclareHeraldry.CacheData;
       HeraldryDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ActiveAttributeDict = DeclareActiveAttribute.CacheData;
       ActiveAttributeDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var StrengthenVfxDict = DeclareStrengthenVfx.CacheData;
       StrengthenVfxDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var KuafuAlchemySkillDict = DeclareKuafuAlchemySkill.CacheData;
       KuafuAlchemySkillDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var DiamondinvestLevelDict = DeclareDiamondinvestLevel.CacheData;
       DiamondinvestLevelDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var EquipDict = DeclareEquip.CacheData;
       EquipDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var HorseUpDict = DeclareHorseUp.CacheData;
       HorseUpDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var EquipSealDict = DeclareEquipSeal.CacheData;
       EquipSealDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var WingAttrDict = DeclareWingAttr.CacheData;
       WingAttrDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var PetLevelDict = DeclarePetLevel.CacheData;
       PetLevelDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GatherDict = DeclareGather.CacheData;
       GatherDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var PowerAnalysisDict = DeclarePowerAnalysis.CacheData;
       PowerAnalysisDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var UIConfigDict = DeclareUIConfig.CacheData;
       UIConfigDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ElementRuneSoulDict = DeclareElementRuneSoul.CacheData;
       ElementRuneSoulDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GmCmdDict = DeclareGmCmd.CacheData;
       GmCmdDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var TaskBranchDict = DeclareTaskBranch.CacheData;
       TaskBranchDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var BagGridDict = DeclareBagGrid.CacheData;
       BagGridDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ScuffleLevelDict = DeclareScuffleLevel.CacheData;
       ScuffleLevelDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var RechargeAwardDict = DeclareRechargeAward.CacheData;
       RechargeAwardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GuildMonsterIntrusionDict = DeclareGuildMonsterIntrusion.CacheData;
       GuildMonsterIntrusionDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ActiveMedalDict = DeclareActiveMedal.CacheData;
       ActiveMedalDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ActivityPromptDict = DeclareActivityPrompt.CacheData;
       ActivityPromptDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var WingUpDict = DeclareWingUp.CacheData;
       WingUpDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var FashionLinkDict = DeclareFashionLink.CacheData;
       FashionLinkDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var VipDict = DeclareVip.CacheData;
       VipDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var PhotoFilterDict = DeclarePhotoFilter.CacheData;
       PhotoFilterDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var SevendayLoginDict = DeclareSevendayLogin.CacheData;
       SevendayLoginDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GuildOfficialDict = DeclareGuildOfficial.CacheData;
       GuildOfficialDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ComboKillDict = DeclareComboKill.CacheData;
       ComboKillDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var HorseMythicalLinkDict = DeclareHorseMythicalLink.CacheData;
       HorseMythicalLinkDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var KaifuGuildlStarcraftDict = DeclareKaifuGuildlStarcraft.CacheData;
       KaifuGuildlStarcraftDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ModelConfigDict = DeclareModelConfig.CacheData;
       ModelConfigDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var SoulBeastsEquipLevelDict = DeclareSoulBeastsEquipLevel.CacheData;
       SoulBeastsEquipLevelDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var EquipSynthesisDict = DeclareEquipSynthesis.CacheData;
       EquipSynthesisDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var TaskEscortDict = DeclareTaskEscort.CacheData;
       TaskEscortDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var WorldQuestionRewardDict = DeclareWorldQuestionReward.CacheData;
       WorldQuestionRewardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var KuafuStatueEvaluateDict = DeclareKuafuStatueEvaluate.CacheData;
       KuafuStatueEvaluateDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GuildFightContinuousRewardDict = DeclareGuildFightContinuousReward.CacheData;
       GuildFightContinuousRewardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var TaskLineDict = DeclareTaskLine.CacheData;
       TaskLineDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var PlayerSkillDict = DeclarePlayerSkill.CacheData;
       PlayerSkillDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var BossgodcloneDict = DeclareBossgodclone.CacheData;
       BossgodcloneDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var KingAllianceSeasonAwardDict = DeclareKingAllianceSeasonAward.CacheData;
       KingAllianceSeasonAwardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ElvesRunelevelDict = DeclareElvesRunelevel.CacheData;
       ElvesRunelevelDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var PlayerGodHeadDict = DeclarePlayerGodHead.CacheData;
       PlayerGodHeadDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var FunctionAlertDict = DeclareFunctionAlert.CacheData;
       FunctionAlertDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var CinematicDict = DeclareCinematic.CacheData;
       CinematicDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var KingFightSeasonAwardDict = DeclareKingFightSeasonAward.CacheData;
       KingFightSeasonAwardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var ShengwuModelDict = DeclareShengwuModel.CacheData;
       ShengwuModelDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var BossGodRuinsMonsterDict = DeclareBossGodRuinsMonster.CacheData;
       BossGodRuinsMonsterDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var SevendaypartystrongDict = DeclareSevendaypartystrong.CacheData;
       SevendaypartystrongDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var JJCAewardDict = DeclareJJCAeward.CacheData;
       JJCAewardDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var FriendItemDict = DeclareFriendItem.CacheData;
       FriendItemDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GmMainFunctionDict = DeclareGmMainFunction.CacheData;
       GmMainFunctionDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var AutoUseMedicineDict = DeclareAutoUseMedicine.CacheData;
       AutoUseMedicineDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var GrowthFundDict = DeclareGrowthFund.CacheData;
       GrowthFundDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var AchievementTypeDict = DeclareAchievementType.CacheData;
       AchievementTypeDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
       var PlayerOccupationDict = DeclarePlayerOccupation.CacheData;
       PlayerOccupationDict = null;
       if(needSleep) System.Threading.Thread.Sleep(sleepLen);
        
    }
  }
}
